package database.model;
// Generated Feb 25, 2015 10:04:42 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Categories generated by hbm2java
 */
public class Categories  implements java.io.Serializable {


     private Integer catid;
     private String catname;
     private Set gameses = new HashSet(0);

    public Categories() {
    }

	
    public Categories(String catname) {
        this.catname = catname;
    }
    public Categories(String catname, Set gameses) {
       this.catname = catname;
       this.gameses = gameses;
    }
   
    public Integer getCatid() {
        return this.catid;
    }
    
    public void setCatid(Integer catid) {
        this.catid = catid;
    }
    public String getCatname() {
        return this.catname;
    }
    
    public void setCatname(String catname) {
        this.catname = catname;
    }
    public Set getGameses() {
        return this.gameses;
    }
    
    public void setGameses(Set gameses) {
        this.gameses = gameses;
    }




}


