package database.model;
// Generated Feb 25, 2015 10:04:42 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Comments generated by hbm2java
 */
public class Comments  implements java.io.Serializable {


     private int id;
     private Games games;
     private Users users;
     private String comment;
     private Date commentdate;

    public Comments() {
    }

    public Comments(int id, Games games, Users users, String comment, Date commentdate) {
       this.id = id;
       this.games = games;
       this.users = users;
       this.comment = comment;
       this.commentdate = commentdate;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Games getGames() {
        return this.games;
    }
    
    public void setGames(Games games) {
        this.games = games;
    }
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }
    public String getComment() {
        return this.comment;
    }
    
    public void setComment(String comment) {
        this.comment = comment;
    }
    public Date getCommentdate() {
        return this.commentdate;
    }
    
    public void setCommentdate(Date commentdate) {
        this.commentdate = commentdate;
    }




}


