package database.model;
// Generated Feb 25, 2015 10:04:42 PM by Hibernate Tools 4.3.1



/**
 * Featured generated by hbm2java
 */
public class Featured  implements java.io.Serializable {


     private int id;
     private Games games;
     private int rank;

    public Featured() {
    }

    public Featured(int id, Games games, int rank) {
       this.id = id;
       this.games = games;
       this.rank = rank;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Games getGames() {
        return this.games;
    }
    
    public void setGames(Games games) {
        this.games = games;
    }
    public int getRank() {
        return this.rank;
    }
    
    public void setRank(int rank) {
        this.rank = rank;
    }




}


