package database.model;
// Generated Feb 25, 2015 10:04:42 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Users generated by hbm2java
 */
public class Users  implements java.io.Serializable {


     private Integer id;
     private String username;
     private String password;
     private String email;
     private int country;
     private int age;
     private Set commentses = new HashSet(0);

    public Users() {
    }

	
    public Users(String username, String password, String email, int country, int age) {
        this.username = username;
        this.password = password;
        this.email = email;
        this.country = country;
        this.age = age;
    }
    public Users(String username, String password, String email, int country, int age, Set commentses) {
       this.username = username;
       this.password = password;
       this.email = email;
       this.country = country;
       this.age = age;
       this.commentses = commentses;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public int getCountry() {
        return this.country;
    }
    
    public void setCountry(int country) {
        this.country = country;
    }
    public int getAge() {
        return this.age;
    }
    
    public void setAge(int age) {
        this.age = age;
    }
    public Set getCommentses() {
        return this.commentses;
    }
    
    public void setCommentses(Set commentses) {
        this.commentses = commentses;
    }




}


